import { BattleDao } from '../infrastructure/typeorm/battle.dao';
import { BattleStatusTypes } from '@app/shared/core/types/settings';

export class Battle {
  constructor(
    readonly player1: string,
    readonly player2: string,
    //readonly date: Date, //No need to store the date in the entity, as it will be generated by the database
    //readonly status: BattleStatusTypes, //ENUM BattleStatus
  ) {}

  
  static fromDao(battleDao: BattleDao): Battle {
    const battle = new Battle(
        battleDao.player1,
        battleDao.player2,
        //battleDao.date,
        //battleDao.status,
    );

    return battle;
  }
}
